name: vaulth_app
description: "Vaultly - ваш персональный цифровой сейф."
publish_to: 'none'

version: 1.0.12+14

environment:
  sdk: ^3.10.9

dependencies:
  flutter:
    sdk: flutter
  shirm_crypto:
    git:
      url: https://github.com/efedotof/vaultly.git
      ref: 7c166e509b69c429dbec8f709eba6f827a656bd2
  cupertino_icons: ^1.0.9
  path_provider: ^2.1.6
  crypto: ^3.0.7
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  flutter_secure_storage: ^11.2.0
  basic_utils: ^5.7.0
  cryptography: ^2.9.0
  device_info_plus: ^13.2.0
  file_picker: ^13.1.0
  logger: ^2.8.0
  shared_preferences: ^2.5.5
  flutter_pdfview: ^1.4.5
  open_filex: ^4.7.0
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  icons_launcher: ^3.1.0
  change_package_name: ^1.1.1
  webcrypto: ^0.6.1
  permission_handler: ^13.0.2
  qr_flutter: ^4.1.0
  sembast: ^3.8.11
  sembast_web: ^2.4.6
  flutter_secure_storage_web: ^2.1.1
  flutter_markdown: ^0.7.7+1
  easy_docs_viewer: ^0.0.2-unstable-release
  pinenacl: ^0.6.0
  ed25519_hd_key: ^2.3.0
  bip39: ^1.0.6
  bip32: ^2.0.0
  flutter_highlight: ^0.7.0
  webview_flutter: ^4.14.1
  webview_flutter_android: ^4.14.1
  webview_flutter_wkwebview: ^3.26.1
  archive: ^4.3.0
  package_info_plus: ^10.2.1
  ffmpeg_kit_flutter_new_min: ^3.6.2
  video_thumbnail_gen: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


icons_launcher:
  image_path: "assets/vaultly_logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    web:
      enable: true
    linux:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/logo_r.png
